# Generated by Django 4.2.11 on 2026-04-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.CharField(blank=True, help_text='საიდენტიფიკაციო კოდი (11 digits)', max_length=11),
        ),
    ]
