# Generated by Django 4.2.11 on 2026-04-21 14:22

import config.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=config.media_utils.user_avatar_path),
        ),
    ]
