# Generated by Django 4.2.11 on 2026-04-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('orders', '0004_order_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
