# Generated by Django 4.2.11 on 2026-04-21 14:22

import config.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_assigned_driver_order_scheduled_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='image',
            field=models.ImageField(upload_to=config.media_utils.order_image_path),
        ),
    ]
