# Generated by Django 4.2.11 on 2026-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_admin_edited_orderedithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedithistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
