# Generated by Django 4.2.11 on 2026-05-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_service_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='is_auto_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
