# Generated by Django 4.2.11 on 2026-04-03 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_add_icon_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mercedes Actros Tow Truck', max_length=200)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, help_text='e.g. 20 tons, 15m3, 5 cars', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in local currency', max_digits=10, null=True)),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, help_text='Per-kilometer rate', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='categories.transportcategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
