# Generated by Django 4.2.11 on 2026-04-29 15:37

from django.db import migrations, models


def promote_first_image_to_primary(apps, schema_editor):
    """For every vehicle that has at least one image, mark the existing
    first one (by current ordering: order asc, created_at asc) as primary
    so the public-facing photo on the landing page doesn't change."""
    VehicleImage = apps.get_model('vehicles', 'VehicleImage')
    Vehicle = apps.get_model('vehicles', 'Vehicle')

    for vehicle_id in Vehicle.objects.values_list('id', flat=True):
        first = (
            VehicleImage.objects.filter(vehicle_id=vehicle_id)
            .order_by('order', 'created_at')
            .first()
        )
        if first is not None:
            VehicleImage.objects.filter(pk=first.pk).update(is_primary=True)


def noop_reverse(apps, schema_editor):
    # Reversal is harmless — the field will be dropped by AddField's reversal.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_image_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(promote_first_image_to_primary, noop_reverse),
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['-is_primary', 'order', 'created_at']},
        ),
    ]
