# Generated by Django 4.2.11 on 2026-04-21 14:22

import config.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=config.media_utils.driver_photo_path),
        ),
    ]
