# Generated by Django 4.2.11 on 2026-04-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcategory',
            name='color',
            field=models.CharField(blank=True, default='#1677ff', help_text='Hex color for the category (e.g. #1677ff)', max_length=7),
        ),
        migrations.AddField(
            model_name='transportcategory',
            name='icon',
            field=models.CharField(blank=True, default='car', help_text='Ant Design icon name (e.g. car, tool, build, thunderbolt, fire-filled)', max_length=50),
        ),
    ]
