# Generated by Django 4.2.11 on 2026-04-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcategory',
            name='requires_destination',
            field=models.BooleanField(default=False, help_text='If true, order needs both pickup and destination (transport). If false, just a work location.'),
        ),
    ]
