# Generated by Django 4.2.11 on 2026-04-21 14:22

import config.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_convert_name_description_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportcategory',
            name='description',
            field=models.JSONField(blank=True, default=dict, help_text='{"en": "...", "ka": "...", "ru": "..."}'),
        ),
        migrations.AlterField(
            model_name='transportcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image (replaces icon when set)', null=True, upload_to=config.media_utils.category_image_path),
        ),
        migrations.AlterField(
            model_name='transportcategory',
            name='name',
            field=models.JSONField(default=dict, help_text='{"en": "...", "ka": "...", "ru": "..."}'),
        ),
    ]
