# Generated by Django 4.2.11 on 2026-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Heawy Way', max_length=200)),
                ('hero_title', models.JSONField(default=dict, help_text='{"en": "...", "ka": "...", "ru": "..."}')),
                ('hero_description', models.JSONField(default=dict)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('stats', models.JSONField(default=list, help_text='[{"number": "500+", "label": {"en": "...", "ka": "...", "ru": "..."}}]')),
                ('steps_title', models.JSONField(default=dict)),
                ('steps', models.JSONField(default=list, help_text='[{"icon": "FileTextOutlined", "title": {...}, "description": {...}}]')),
                ('benefits_title', models.JSONField(default=dict)),
                ('benefits', models.JSONField(default=list, help_text='[{"icon": "RocketOutlined", "title": {...}, "description": {...}, "color": "#00B856"}]')),
                ('cta_title', models.JSONField(default=dict)),
                ('cta_description', models.JSONField(default=dict)),
                ('cta_button_text', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Settings',
                'verbose_name_plural': 'Landing Page Settings',
            },
        ),
    ]
