# Generated by Django 4.2.11 on 2026-04-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesettings',
            name='search_countries',
            field=models.JSONField(blank=True, default=list, help_text='List of ISO country codes when scope is "custom", e.g. ["ge","tr","az"]'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='search_scope',
            field=models.CharField(choices=[('georgia', 'Georgia only'), ('worldwide', 'Worldwide'), ('custom', 'Custom countries')], default='georgia', help_text='Controls which countries are available in location search', max_length=20),
        ),
    ]
