# Generated by Django 4.2.11 on 2026-04-21 14:22

import config.media_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_add_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab favicon (recommended: 32x32 or 64x64 PNG)', null=True, upload_to=config.media_utils.landing_favicon_path),
        ),
        migrations.AlterField(
            model_name='landingpagesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=config.media_utils.landing_hero_path),
        ),
        migrations.AlterField(
            model_name='landingpagesettings',
            name='site_icon',
            field=models.ImageField(blank=True, help_text='Website logo/icon shown in navbar', null=True, upload_to=config.media_utils.landing_site_icon_path),
        ),
    ]
